# Generated by Django 6.0.6 on 2026-06-24 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('relationship_tag', models.CharField(choices=[('FRIEND', 'Friend'), ('RELATIVE', 'Relative'), ('COLLEAGUE', 'Colleague'), ('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('BANK', 'Bank'), ('NBFC', 'NBFC'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('space_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('BUSINESS', 'Business')], default='PERSONAL', max_length=20)),
                ('space_visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared')], default='PRIVATE', max_length=20)),
                ('currency_code', models.CharField(default='INR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spaces',
            },
        ),
        migrations.CreateModel(
            name='SpaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('VIEWER', 'Viewer'), ('FIELDMAN', 'FieldMan')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to='api.spacemember')),
            ],
            options={
                'db_table': 'space_members',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('notification_prefs', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('GIVEN', 'Given'), ('TAKEN', 'Taken')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('closure_reason', models.CharField(blank=True, choices=[('FULLY_PAID', 'Fully Paid'), ('SETTLED', 'Settled'), ('WRITTEN_OFF', 'Written Off'), ('MANUALLY_CLOSED', 'Manually Closed')], max_length=20, null=True)),
                ('closure_note', models.TextField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('written_off_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('start_date', models.DateTimeField()),
                ('first_due_date', models.DateField(blank=True, null=True)),
                ('tenure_periods', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interest_type', models.CharField(choices=[('NONE', 'No Interest'), ('FIXED', 'Fixed Amount'), ('FLAT', 'Flat Rate'), ('REDUCING_BALANCE', 'Reducing Balance'), ('COMPOUND', 'Compound'), ('CUSTOM', 'Custom Interest')], max_length=20)),
                ('rate_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rate_period', models.CharField(blank=True, choices=[('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly'), ('YEAR', 'Yearly')], max_length=10, null=True)),
                ('fixed_interest_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fixed_interest_frequency', models.CharField(blank=True, choices=[('ONE_TIME', 'One Time'), ('RECURRING', 'Recurring')], max_length=20, null=True)),
                ('interest_timing', models.CharField(choices=[('COLLECTED_UPFRONT', 'Collected Upfront'), ('DEDUCTED_FROM_DISBURSEMENT', 'Deducted From Disbursement'), ('PAYABLE_AT_END', 'Payable at End'), ('PAYABLE_PERIODICALLY', 'Payable Periodically')], default='PAYABLE_PERIODICALLY', max_length=30)),
                ('net_disbursed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('interest_rate_behavior', models.CharField(choices=[('FIXED', 'Fixed'), ('VARIABLE', 'Variable'), ('PROMOTIONAL', 'Promotional')], default='FIXED', max_length=20)),
                ('promo_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('promo_period_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('repayment_type', models.CharField(choices=[('ONE_TIME', 'One-time (Bullet)'), ('EMI', 'EMI'), ('INTEREST_ONLY', 'Interest Only'), ('PRINCIPAL_ONLY', 'Principal Only'), ('FLEXIBLE', 'Flexible'), ('CUSTOM_INSTALLMENTS', 'Custom Installments')], max_length=20)),
                ('has_balloon_final_payment', models.BooleanField(default=False)),
                ('payment_frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20, null=True)),
                ('payment_timing_rule', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ANYTIME', 'Anytime')], default='SCHEDULED', max_length=20)),
                ('advance_payment_mode', models.CharField(choices=[('CARRY_FORWARD_CREDIT', 'Carry Forward Credit'), ('RECALCULATE_SCHEDULE', 'Recalculate Schedule')], max_length=30)),
                ('advance_credit_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('penalty_type', models.CharField(choices=[('NONE', 'None'), ('FIXED', 'Fixed Penalty'), ('PERCENTAGE', 'Percentage Penalty'), ('DAILY_LATE_FEE', 'Daily Late Fee'), ('MONTHLY_LATE_FEE', 'Monthly Late Fee'), ('EXTRA_INTEREST', 'Extra Interest')], default='NONE', max_length=20)),
                ('penalty_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('grace_period_days', models.PositiveSmallIntegerField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='loans', to='api.contact')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='SpaceSettings',
            fields=[
                ('space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='api.space')),
                ('default_interest_type', models.CharField(choices=[('NONE', 'No Interest'), ('FIXED', 'Fixed Amount'), ('FLAT', 'Flat Rate'), ('REDUCING_BALANCE', 'Reducing Balance'), ('COMPOUND', 'Compound'), ('CUSTOM', 'Custom Interest')], default='NONE', max_length=20)),
                ('default_rate_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('default_rate_period', models.CharField(blank=True, choices=[('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly'), ('YEAR', 'Yearly')], max_length=10, null=True)),
                ('default_repayment_type', models.CharField(choices=[('ONE_TIME', 'One-time (Bullet)'), ('EMI', 'EMI'), ('INTEREST_ONLY', 'Interest Only'), ('PRINCIPAL_ONLY', 'Principal Only'), ('FLEXIBLE', 'Flexible'), ('CUSTOM_INSTALLMENTS', 'Custom Installments')], default='EMI', max_length=20)),
                ('default_payment_frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20, null=True)),
                ('default_advance_payment_mode', models.CharField(choices=[('CARRY_FORWARD_CREDIT', 'Carry Forward Credit'), ('RECALCULATE_SCHEDULE', 'Recalculate Schedule')], default='CARRY_FORWARD_CREDIT', max_length=30)),
                ('default_penalty_type', models.CharField(choices=[('NONE', 'None'), ('FIXED', 'Fixed Penalty'), ('PERCENTAGE', 'Percentage Penalty'), ('DAILY_LATE_FEE', 'Daily Late Fee'), ('MONTHLY_LATE_FEE', 'Monthly Late Fee'), ('EXTRA_INTEREST', 'Extra Interest')], default='NONE', max_length=20)),
                ('default_grace_period_days', models.PositiveSmallIntegerField(default=0)),
                ('deduct_expenses_from_reports', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'space_settings',
            },
        ),
        migrations.AddField(
            model_name='space',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RepaymentScheduleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_version', models.PositiveSmallIntegerField(default=1)),
                ('line_no', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('is_current_version', models.BooleanField(default=True)),
                ('superseded_by_type', models.CharField(blank=True, max_length=30, null=True)),
                ('superseded_by_id', models.BigIntegerField(blank=True, null=True)),
                ('is_custom_line', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_lines', to='api.loan')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.space')),
            ],
            options={
                'db_table': 'repayment_schedule_lines',
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='api.space'),
        ),
        migrations.AddField(
            model_name='contact',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.space'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.space'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_MADE', 'Payment Made'), ('INTEREST_RECEIVED', 'Interest Received'), ('INTEREST_PAID', 'Interest Paid'), ('PENALTY_RECEIVED', 'Penalty Received'), ('PENALTY_PAID', 'Penalty Paid'), ('DISBURSEMENT', 'Disbursement'), ('SETTLEMENT', 'Settlement'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_date', models.DateTimeField()),
                ('collection_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('AUTO_DEBIT', 'Auto Debit'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('adjustment_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.loan')),
                ('reverses_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by_transactions', to='api.transaction')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.space')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.spacemember')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.AddField(
            model_name='spacemember',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.space'),
        ),
        migrations.AddField(
            model_name='spacemember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SpaceInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='api.spacemember')),
            ],
            options={
                'db_table': 'space_invites',
            },
        ),
        migrations.CreateModel(
            name='LoanWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiver_type', models.CharField(choices=[('INTEREST', 'Interest'), ('PENALTY', 'Penalty')], max_length=10)),
                ('waived_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='api.loan')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.space')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.spacemember')),
            ],
            options={
                'db_table': 'loan_waivers',
            },
        ),
        migrations.CreateModel(
            name='LoanTenureExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_periods', models.PositiveSmallIntegerField()),
                ('tenure_periods_before', models.PositiveSmallIntegerField()),
                ('tenure_periods_after', models.PositiveSmallIntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenure_extensions', to='api.loan')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.space')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.spacemember')),
            ],
            options={
                'db_table': 'loan_tenure_extensions',
            },
        ),
        migrations.CreateModel(
            name='LoanRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('rate_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rate_period', models.CharField(choices=[('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly'), ('YEAR', 'Yearly')], max_length=10)),
                ('trigger', models.CharField(choices=[('INITIAL', 'Initial'), ('VARIABLE_CHANGE', 'Variable Change'), ('PROMO_EXPIRY', 'Promotional Expiry'), ('RESTRUCTURING', 'Restructuring')], max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='api.loan')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.space')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.spacemember')),
            ],
            options={
                'db_table': 'loan_rate_history',
            },
        ),
        migrations.CreateModel(
            name='LoanMoratorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause_start_date', models.DateField()),
                ('pause_end_date', models.DateField()),
                ('interest_free', models.BooleanField(default=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moratoriums', to='api.loan')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.space')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.spacemember')),
            ],
            options={
                'db_table': 'loan_moratoriums',
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans_closed', to='api.spacemember'),
        ),
        migrations.AddField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans_created', to='api.spacemember'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DOCUMENTATION', 'Documentation'), ('TRAVEL', 'Travel'), ('LEGAL', 'Legal'), ('COLLECTION', 'Collection'), ('PROCESSING', 'Processing'), ('MISCELLANEOUS', 'Miscellaneous')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expense_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.loan')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.space')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.spacemember')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('LOAN', 'Loan'), ('CONTACT', 'Contact')], max_length=20)),
                ('entity_id', models.BigIntegerField()),
                ('document_type', models.CharField(choices=[('AGREEMENT', 'Agreement'), ('ID_PROOF', 'Identity Proof'), ('PROMISSORY_NOTE', 'Promissory Note'), ('RECEIPT', 'Receipt'), ('CHEQUE_IMAGE', 'Cheque Image'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.space')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.spacemember')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('disbursement_date', models.DateTimeField()),
                ('sequence_no', models.PositiveSmallIntegerField()),
                ('label', models.CharField(choices=[('ORIGINAL', 'Original'), ('TOP_UP', 'Top-up'), ('ADDITIONAL_BORROWING', 'Additional Borrowing')], default='ORIGINAL', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='api.loan')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.space')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.spacemember')),
            ],
            options={
                'db_table': 'disbursements',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts_created', to='api.spacemember'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=60)),
                ('entity_type', models.CharField(choices=[('LOAN', 'Loan'), ('CONTACT', 'Contact'), ('TRANSACTION', 'Transaction'), ('SPACE_MEMBER', 'Space Member'), ('SPACE', 'Space'), ('EXPENSE', 'Expense'), ('SPACE_PARTNER', 'Space Partner')], max_length=20)),
                ('entity_id', models.BigIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.space')),
                ('actor_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='api.spacemember')),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
        migrations.CreateModel(
            name='SpacePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_contribution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('profit_share_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.spacemember')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='api.space')),
                ('space_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to='api.spacemember')),
            ],
            options={
                'db_table': 'space_partners',
            },
        ),
        migrations.CreateModel(
            name='PartnerCapitalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('WITHDRAWAL', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.space')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.spacemember')),
                ('space_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_transactions', to='api.spacepartner')),
            ],
            options={
                'db_table': 'partner_capital_transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_component', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('interest_component', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('penalty_component', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.repaymentscheduleline')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.space')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.transaction')),
            ],
            options={
                'db_table': 'transaction_allocations',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settlement_detail', serialize=False, to='api.transaction')),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('outstanding_balance_at_settlement', models.DecimalField(decimal_places=2, max_digits=14)),
                ('settlement_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('forgiven_amount_field', models.DecimalField(db_column='forgiven_amount', decimal_places=2, editable=False, max_digits=14)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.loan')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.space')),
            ],
            options={
                'db_table': 'settlements',
            },
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['owner'], name='spaces_owner_i_d4edf0_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentscheduleline',
            index=models.Index(fields=['loan', 'is_current_version', 'status', 'due_date'], name='repayment_s_loan_id_05e90a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['loan', 'transaction_date'], name='transaction_loan_id_bcc3e6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['space', 'transaction_date'], name='transaction_space_i_c2570d_idx'),
        ),
        migrations.AddIndex(
            model_name='spacemember',
            index=models.Index(fields=['space'], name='space_membe_space_i_738ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='spacemember',
            index=models.Index(fields=['user'], name='space_membe_user_id_1ab52f_idx'),
        ),
        migrations.AddConstraint(
            model_name='spacemember',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False), models.Q(('status', 'REMOVED'), _negated=True)), fields=('space', 'user'), name='unique_active_space_user'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['space'], name='loans_space_i_c31285_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['space', 'status'], name='loans_space_i_54316b_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['space', 'contact'], name='loans_space_i_90caeb_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['space', 'direction', 'status'], name='loans_space_i_0c8b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['space'], name='contacts_space_i_ce1315_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['space', 'created_at'], name='activity_lo_space_i_8b4d66_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='activity_lo_entity__2a2d99_idx'),
        ),
    ]
