# Generated by Django 6.0.6 on 2026-06-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacesettings',
            name='default_advance_payment_mode',
            field=models.CharField(default='CARRY_FORWARD_CREDIT', max_length=30),
        ),
        migrations.AlterField(
            model_name='spacesettings',
            name='default_interest_type',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='spacesettings',
            name='default_payment_frequency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spacesettings',
            name='default_penalty_type',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='spacesettings',
            name='default_rate_period',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='spacesettings',
            name='default_repayment_type',
            field=models.CharField(default='EMI', max_length=20),
        ),
    ]
